version: '3.1'

services:

  mysql:
    build: ./database/
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=basicDataBase
      - MYSQL_ROOT_PASSWORD=senha
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  lambda:
    tty: true
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    command: 
      - /bin/sh
      - -c
      - |
        export DATABASE=basicDataBase_dev
        # npm test
        serverless offline
    environment:
      - HOST=mysql
      - PORT=3306
      - USERNAME=root
      - PASSWORD=senha
    volumes:
      - .:/usr/src/app/
